### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Erdal-oz** [adamantii/objection.py#3]
It is hard to understand hundreds/thousands of lines of code someone else wrote without documentation you know

**Comment by Erdal-oz** [comment]
https://blog.submain.com/code-documentation-the-complete-beginners-guide/

**Comment by Erdal-oz** [comment]
this would also help your future self looking at the code 3 months later

**Comment by Erdal-oz** [comment]
> we're getting there...
consider enabling wikis

**Comment by adamantii** [comment]
Published the docs (357c7f1f5a27efc1ea23440c99f24c0430e0b501)
