### ISSUE TITLE
are you using Egg for packaging?

### ISSUE THREAD

**Issue by Erdal-oz** [adamantii/objection.py#4]
https://packaging.python.org/en/latest/discussions/wheel-vs-egg/

**Comment by Erdal-oz** [comment]
egg has been deprecated for wheel

**Comment by adamantii** [comment]
hmm I think I was using an outdated guide

**Comment by Erdal-oz** [comment]
> hmm I think I was using an outdated guide
> 
> I can update it later (by following a different guide that's from 2022 :P)

 \
what about using the official guide lmao https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by adamantii** [comment]
Closed by #5
